include ../../config.mk

# Needed for include generation and library name
PROJECT_NAME = ncl-presenter

CFLAGS += $(DFB_CFLAGS) $(LUA_CFLAGS) -I../../build/include/lifia -I../telemidia-links -I.

include ../../rules.mk
