include ../../config.mk

# Needed for include generation and library name
PROJECT_NAME = connector

CFLAGS 	+= $(DFB_CFLAGS) -I../../build/include/lifia -I../telemidia-links -Iinclude -I.

include ../../rules.mk
